'use strict';


function getAutoGeneratedName(url, callback){
	var xmlHttp = new XMLHttpRequest();
	xmlHttp.onreadystatechange = function(){
		if(xmlHttp.readyState == 4 && xmlHttp.status == 200){
			try{
				var data = JSON.parse(xmlHttp.responseText);
			} catch(err) {
				console.log(err.message + "->" + xmlHttp.responseText);
				return;
			}
			callback(data);
		}
	};
	xmlHttp.open("GET", url, true);
	xmlHttp.send();
}


/***** Everytime the page is loaded and hamster create/buy button is clicked, get a new name using API and update html *****/

//set value for hamster name in html
function setName(){
	getAutoGeneratedName('https://randomuser.me/api/?inc=name',
		function(data){
		var firstName = data.results[0].name.first;
		var firstCharUpper = firstName.charAt(0).toUpperCase();
		// Set the value for hamster name
		document.getElementById("hamsterName").value = firstCharUpper + firstName.slice(1);});
}

// Set the event listener for create/buy buttons
if (document.getElementById("submitButton")) {
	var submitButton = document.getElementById("submitButton");
	submitButton.addEventListener('click', setName, false);
};


// when the page is loaded, set name
setName();

