function getAutoGeneratedName(url, callback){
	var xmlHttp = new XMLHttpRequest();
	xmlHttp.onreadystatechange = function(){
		if(xmlHttp.readyState == 4 && xmlHttp.status == 200){
			try{
				var data = JSON.parse(xmlHttp.responseText);
			} catch(err) {
				console.log(err.message + "->" + xmlHttp.responseText);
				return;
			}
			callback(data);
		}
	};
	xmlHttp.open("GET", url, true);
	xmlHttp.send();
}


/***** Event to set value of hamster name in HTML to auto gengrated name using api *****/ 

// event function
function setName() {
	getAutoGeneratedName('https://randomuser.me/api/?inc=name', function(data){
		var firstName = data.results[0].name.first;
		var firstCharUpper = firstName.charAt(0).toUpperCase();
	
		// Set the value for hamster name
		document.getElementById("hamsterName").value = firstCharUpper + firstName.slice(1);
	});
}


// Set the event listener for start button and hamster tub
if (document.getElementById("startButton")) {
	var startButton = document.getElementById("startButton");
	startButton.addEventListener('click', setName, false);
};
if (document.getElementById("hamsterTab")) {
	var hamsterTab = document.getElementById("hamsterTab");
	hamsterTab.addEventListener('click', setName, false);
};



